# Generated by Django 5.0 on 2023-12-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightskuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ClientUser',
        ),
    ]
